# Generated by Django 5.2.11 on 2026-08-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('truth', 'Truth'), ('dare', 'Dare')], max_length=10)),
                ('category', models.CharField(choices=[('funny', 'Funny'), ('fantasy', 'Fantasy'), ('crazy', 'Crazy'), ('friendship', 'Friendship'), ('deep', 'Deep'), ('horror', 'Horror'), ('movies', 'Movies'), ('music', 'Music'), ('school', 'School / College'), ('random', 'Random')], max_length=20)),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
