# Generated by Django 5.2.11 on 2026-08-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_question_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=6, unique=True)),
                ('host_name', models.CharField(max_length=50)),
                ('players', models.JSONField(default=list)),
                ('selected_categories', models.JSONField(default=list)),
                ('difficulty', models.CharField(default='mixed', max_length=10)),
                ('current_player_index', models.IntegerField(default=0)),
                ('current_question_id', models.IntegerField(blank=True, null=True)),
                ('game_started', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
