# Generated by Django 5.2.11 on 2026-08-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_customquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customquestion',
            name='category',
            field=models.CharField(choices=[('funny', 'Funny'), ('fantasy', 'Fantasy'), ('crazy', 'Crazy'), ('friendship', 'Friendship'), ('deep', 'Deep'), ('horror', 'Horror'), ('movies', 'Movies'), ('music', 'Music'), ('school', 'School / College'), ('random', 'Random')], default='random', max_length=20),
        ),
        migrations.AddField(
            model_name='customquestion',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
