# Generated by Django 5.2.11 on 2026-08-31 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_customquestion_category_customquestion_difficulty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineRoom',
        ),
    ]
